services:
  qdrant:
    environment:
      QDRANT__TELEMETRY_DISABLED: "true"
    volumes:
      - qdrant-ci-data:/qdrant/storage

  ollama:
    volumes:
      - ollama-ci-data:/root/.ollama
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  qdrant-ci-data:
  ollama-ci-data: